---
- name: Install Postgresql dependencies
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items:
    - libpq-dev

- name: Install Postgresql server and client
  apt: pkg={{ item }}-{{ postgresql.version }} state=installed update-cache=yes
  register: postgresql_install
  with_items:
    - postgresql
    - postgresql-server-dev
  tags:
    - packages

- name: Install PostgreSQL hba config file
  template: src=pg_hba.conf
            dest=/etc/postgresql/{{ postgresql.version }}/main/pg_hba.conf
            owner={{ postgresql.user }} group={{ postgresql.group }}

- name: Install PostgreSQL config file
  template: src=postgresql.conf
            dest=/etc/postgresql/{{ postgresql.version }}/main/postgresql.conf
            owner={{ postgresql.user }} group={{ postgresql.group }}
  notify:
    - restart postgresql
  tags:
    - configuration
